//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysProgAnket3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ders_Detaylari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ders_Detaylari()
        {
            this.Dersler = new HashSet<Dersler>();
            this.Ogrenci_Ders = new HashSet<Ogrenci_Ders>();
        }
    
        public int ders_kodu { get; set; }
        public string ders_adi { get; set; }
        public Nullable<int> teori { get; set; }
        public Nullable<int> pratik { get; set; }
        public Nullable<int> lab { get; set; }
        public Nullable<int> toplam_kredi { get; set; }
        public Nullable<int> acan_bolum_kodu { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dersler> Dersler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogrenci_Ders> Ogrenci_Ders { get; set; }
    }
}
