//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysProgAnket3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        public Nullable<int> ders_kodu { get; set; }
        public int grup_no { get; set; }
        public string dersin_adi { get; set; }
        public Nullable<int> hoca_kodu { get; set; }
    
        public virtual Ders_Detaylari Ders_Detaylari { get; set; }
        public virtual Hocalar Hocalar { get; set; }
    }
}
