//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysProgAnket3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci_Ders
    {
        public int id { get; set; }
        public int ogr_no { get; set; }
        public int ders_kodu { get; set; }
        public int grubu { get; set; }
        public string ders_adi { get; set; }
    
        public virtual Ders_Detaylari Ders_Detaylari { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
