//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysProgAnket3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysProgDbEntities : DbContext
    {
        public SysProgDbEntities()
            : base("name=SysProgDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolumler> Bolumler { get; set; }
        public virtual DbSet<Ders_Detaylari> Ders_Detaylari { get; set; }
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<Fakulteler> Fakulteler { get; set; }
        public virtual DbSet<Hocalar> Hocalar { get; set; }
        public virtual DbSet<Ogrenci_Ders> Ogrenci_Ders { get; set; }
        public virtual DbSet<Ogrenciler> Ogrenciler { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
